#!/bin/bash

# Quick example of assigning a variable
NAME="AGNEY_PATEL"
echo $NAME

# Change variable value
NAME="agn3y"
echo $NAME

# Take input from user
echo "Please enter your name: "
read NAME
echo "The name you entered is: $NAME"

# Including conditional logic
echo "What would you like to eat?"
echo -e "1. VADAPAV\n2. PAVBHAJI"
read CHOICE

if [[ $CHOICE == 1 ]]; then
    echo "You Have Chosen VADAPAV"
elif [[ $CHOICE == 2 ]]; then
    echo "You Have Chosen PAVBHAJI"
else
    echo "Invalid choice"
fi

# if, elif and else logic
echo "Kaisan ba?"
echo -e "1. Bihari\n2. Bhojpuri"
read CHOICE2

if [[ $CHOICE2 == 1 ]]; then
    echo "Bihari selected"
elif [[ $CHOICE2 == 2 ]]; then
    echo "Mai ke chodo"
else
    echo "Invalid selection"
fi
